version: '3'
services:
  botpopup:
    image: node:9
    working_dir: /app
    command: "bash ./start.sh"
    env_file:
      - ./config/common.env
    ports:
      - 8080:8080
    volumes:
      - ./:/app
      - node-modules-cache:/app/node_modules
  ngrok:
    image: fnichol/ngrok
    command: "botpopup:8080"
    links:
      - botpopup:http
    ports:
      - 4040:4040
volumes:
  node-modules-cache:
